all:
	go mod tidy
	go mod tidy -modfile=tools.mod
	go generate -x ./...
	go tool -modfile=tools.mod golangci-lint fmt ./...
	go test -count=1 -race ./...
	go tool -modfile=tools.mod golangci-lint run ./...
