// Package shoulda provides an assertion library that is as simple as possible, but not simpler.
package shoulda

import (
	"regexp"
	"testing"

	"github.com/sanity-io/litter"

	"github.com/AlekSi/shoulda/internal"
)

// TB is a subset of [testing.TB] that is used by this package.
type TB interface {
	Helper()
	Log(args ...any)
	Fail()
	FailNow()
}

// dumpConfig contains the configuration used by the default default [Dump].
var dumpConfig = &litter.Options{
	Compact:                   false,
	StripPackageNames:         false,
	HidePrivateFields:         true,
	HideZeroValues:            false,
	FieldExclusions:           regexp.MustCompile(`^(XXX_.*)$`), // XXX_ is a prefix of fields generated by protoc-gen-go
	FieldFilter:               nil,
	HomePackage:               "",
	Separator:                 " ",
	StrictGo:                  false,
	DumpFunc:                  nil,
	DisablePointerReplacement: false,
	FormatTime:                false,
}

// Dump returns the textual representation of v.
var Dump = func(tb TB, v any) string {
	tb.Helper()

	return dumpConfig.Sdump(v)
}

// Diff returns a diff between actual and expected.
var Diff = func(tb TB, actualName string, actual []byte, expectedName string, expected []byte) []byte {
	tb.Helper()

	return diff(expectedName, expected, actualName, actual)
}

// assert returns true if condition is true;
// otherwise it logs msg, fails test, and returns false.
func assert(tb TB, condition bool, msg internal.Messager) bool {
	tb.Helper()

	if condition {
		return true
	}

	tb.Log(msg.Message())
	tb.Fail()
	return false
}

// check interfaces
var (
	_ TB = (testing.TB)(nil)
	_ TB = internal.TestTB{}
)
