package shoulda

import (
	"fmt"
	"regexp"
	"strings"
	"testing"

	"github.com/sanity-io/litter"

	"github.com/AlekSi/shoulda/internal"
	"github.com/AlekSi/shoulda/internal/diff"
)

// TB is a subset of [testing.TB] that is used by this package.
type TB interface {
	Helper()
	Log(args ...any)
	Fail()
	FailNow()
}

// defaultDumpConfig contains the configuration used by the default [Dump].
var defaultDumpConfig = &litter.Options{
	Compact:                   false,
	StripPackageNames:         false,
	HidePrivateFields:         false,
	HideZeroValues:            false,
	FieldExclusions:           regexp.MustCompile(`^(XXX_.*)$`), // XXX_ is a prefix of fields generated by protoc-gen-go
	FieldFilter:               nil,
	HomePackage:               "",
	Separator:                 " ",
	StrictGo:                  false, // at least until https://github.com/sanity-io/litter/issues/59 is resolved
	DumpFunc:                  nil,
	DisablePointerReplacement: false,
	FormatTime:                true,
}

// Dump returns the textual representation of v.
var Dump func(tb TB, v any) string = defaultDump

// defaultDump is the default implementation of [Dump].
func defaultDump(tb TB, v any) string {
	tb.Helper()

	// Include %T since litter does not always include type
	// For example, Sdump(int(13)) and Sdump(uint(13)) produce the same result.
	return fmt.Sprintf("%s (%T)", defaultDumpConfig.Sdump(v), v)
}

// Diff returns a diff between actual and expected.
var Diff func(tb TB, actualName string, actual any, expectedName string, expected any) string = defaultDiff

// defaultDiff is the default implementation of [Diff].
func defaultDiff(tb TB, actualName string, actual any, expectedName string, expected any) string {
	tb.Helper()

	a := strings.TrimRight(Dump(tb, actual), "\n") + "\n"
	e := strings.TrimRight(Dump(tb, expected), "\n") + "\n"
	d := diff.Diff(expectedName, []byte(e), actualName, []byte(a))
	return strings.TrimRight(string(d), "\n")
}

// assert returns true if condition is true;
// otherwise it logs m, fails test, and returns false.
func assert(tb TB, condition bool, m messager) bool {
	tb.Helper()

	if condition {
		return true
	}

	tb.Log(m.Message())
	tb.Fail()
	return false
}

// check interfaces
var (
	_ TB = (testing.TB)(nil)
	_ TB = internal.TestTB{}
)
