//go:build ignore

package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

const generatedHeader = "// Code generated by gen.go. DO NOT EDIT.\n\n"

const compareTemplate = generatedHeader + `

package musta

import (
	"github.com/AlekSi/shoulda"

	"github.com/AlekSi/shoulda/cmp"
)

{{range .Functions}}

{{range .CommentLines}}// {{.}}
{{end -}}
func {{.Name}}{{.TypeParams}}({{.Params}}) {
	tb.Helper()

	if !shoulda.{{.Name}}({{.Args}}) {
		tb.FailNow()
	}
}

{{end}}
`

// templateData contains data for compare.go template.
type templateData struct {
	Functions []functionData
}

// functionData contains data for a single generated wrapper.
type functionData struct {
	CommentLines []string
	Name         string
	TypeParams   string
	Params       string
	Args         string
}

// main rewrites compare wrappers and test analogues for the musta package.
func main() {
	flag.Parse()

	data, err := parseCompare(filepath.Join("..", "..", "compare.go"))
	if err != nil {
		log.Fatal(err)
	}

	src, err := render(data)
	if err != nil {
		log.Fatal(err)
	}

	if err := os.WriteFile("compare.go", src, 0o644); err != nil {
		log.Fatal(err)
	}

	for _, testFile := range []string{
		"compare_test.go",
		"compare_example_test.go",
	} {
		if err := rewriteTestFile(filepath.Join("..", "..", testFile)); err != nil {
			log.Fatal(err)
		}
	}
}

// parseCompare collects exported compare helpers that should be wrapped by musta.
func parseCompare(comparePath string) (templateData, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, comparePath, nil, parser.ParseComments)
	if err != nil {
		return templateData{}, fmt.Errorf("parse %s: %w", comparePath, err)
	}

	var functions []functionData
	for _, decl := range file.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok {
			continue
		}

		if !fn.Name.IsExported() {
			continue
		}

		data, err := collectFunction(fset, fn)
		if err != nil {
			return templateData{}, fmt.Errorf("collect %s: %w", fn.Name.Name, err)
		}

		functions = append(functions, data)
	}

	if len(functions) == 0 {
		return templateData{}, fmt.Errorf("no wrapper candidates found in %s", comparePath)
	}

	return templateData{Functions: functions}, nil
}

// collectFunction builds template data for a wrapped function.
func collectFunction(fset *token.FileSet, fn *ast.FuncDecl) (functionData, error) {
	res := functionData{
		CommentLines: strings.Split(strings.TrimSuffix(fn.Doc.Text(), "\n"), "\n"),
		Name:         fn.Name.Name,
	}

	if fields := fn.Type.TypeParams; fields != nil && len(fields.List) != 0 {
		parts := make([]string, 0, len(fields.List))
		for _, field := range fields.List {
			part, _, err := renderField(fset, field)
			if err != nil {
				return functionData{}, err
			}

			parts = append(parts, part)
		}

		res.TypeParams = "[" + strings.Join(parts, ", ") + "]"
	}

	var err error
	res.Params, res.Args, err = renderParams(fset, fn.Type.Params)
	return res, err
}

// renderParams renders the wrapper parameter list and call arguments.
func renderParams(fset *token.FileSet, fields *ast.FieldList) (string, string, error) {
	if fields == nil || len(fields.List) == 0 {
		return "", "", nil
	}

	params := make([]string, 0, len(fields.List))
	args := make([]string, 0, len(fields.List))
	for _, field := range fields.List {
		param, fieldArgs, err := renderField(fset, field)
		if err != nil {
			return "", "", err
		}

		params = append(params, param)
		args = append(args, fieldArgs...)
	}

	return strings.Join(params, ", "), strings.Join(args, ", "), nil
}

// renderField renders a single parameter field and the argument names it contributes.
func renderField(fset *token.FileSet, field *ast.Field) (string, []string, error) {
	if len(field.Names) == 0 {
		return "", nil, fmt.Errorf("unnamed parameters are not supported")
	}

	var typeBuf bytes.Buffer
	if err := printer.Fprint(&typeBuf, fset, field.Type); err != nil {
		return "", nil, err
	}

	names := make([]string, 0, len(field.Names))
	for _, ident := range field.Names {
		names = append(names, ident.Name)
	}

	return strings.Join(names, ", ") + " " + typeBuf.String(), names, nil
}

// render executes the compare template and formats the generated source.
func render(data templateData) ([]byte, error) {
	tmpl, err := template.New("compare").Parse(compareTemplate)
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, err
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, err
	}

	return formatted, nil
}

// rewriteTestFile rewrites a shoulda test file as its musta analogue.
func rewriteTestFile(srcPath string) error {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, srcPath, nil, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("rewriteTestFile: parse %s: %w", srcPath, err)
	}

	file.Name = ast.NewIdent("musta")

	var buf bytes.Buffer
	buf.WriteString(generatedHeader)

	if err := format.Node(&buf, fset, file); err != nil {
		return fmt.Errorf("rewriteTestFile: format %s: %w", srcPath, err)
	}

	dstPath := filepath.Base(srcPath)
	if err := os.WriteFile(dstPath, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("rewriteTestFile: write %s: %w", dstPath, err)
	}

	return nil
}
