//go:build ignore

package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"log"
	"os"
	"path"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"text/template"
)

const compareTemplate = `// Code generated by gen.go; DO NOT EDIT.

package musta

import (
{{range .Imports}}
	{{.}}
{{end}}
)
{{range .Functions}}
{{range .CommentLines}}// {{.}}
{{end}}func {{.Name}}{{.TypeParams}}({{.Params}}) {
	tb.Helper()

	if !shoulda.{{.Name}}({{.Args}}) {
		tb.FailNow()
	}
}
{{end}}`

// templateData contains data for compare.go template.
type templateData struct {
	Imports   []string
	Functions []functionData
}

// functionData contains data for a single generated wrapper.
type functionData struct {
	CommentLines []string
	Name         string
	TypeParams   string
	Params       string
	Args         string
}

// main rewrites compare.go wrappers for the musta package.
func main() {
	flag.Parse()

	_, genPath, _, ok := runtime.Caller(0)
	if !ok {
		log.Fatal("failed to resolve generator path")
	}

	genDir := filepath.Dir(genPath)
	rootDir := filepath.Clean(filepath.Join(genDir, "..", ".."))
	comparePath := filepath.Join(rootDir, "compare.go")
	outputPath := filepath.Join(genDir, "compare.go")

	data, err := parseCompare(comparePath)
	if err != nil {
		log.Fatal(err)
	}

	src, err := render(data)
	if err != nil {
		log.Fatal(err)
	}

	if err := os.WriteFile(outputPath, src, 0o644); err != nil {
		log.Fatal(err)
	}
}

// parseCompare collects exported compare helpers that should be wrapped by musta.
func parseCompare(comparePath string) (templateData, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, comparePath, nil, parser.ParseComments)
	if err != nil {
		return templateData{}, fmt.Errorf("parse %s: %w", comparePath, err)
	}

	imports, err := availableImports(fset, file)
	if err != nil {
		return templateData{}, err
	}

	var functions []functionData
	usedImports := map[string]struct{}{
		`"github.com/AlekSi/shoulda"`: {},
	}
	for _, decl := range file.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || !shouldWrap(fn) {
			continue
		}

		data, err := collectFunction(fset, fn)
		if err != nil {
			return templateData{}, fmt.Errorf("collect %s: %w", fn.Name.Name, err)
		}

		functions = append(functions, data)
		collectUsedImports(imports, fn.Type.TypeParams, usedImports)
		collectUsedImports(imports, fn.Type.Params, usedImports)
	}

	if len(functions) == 0 {
		return templateData{}, fmt.Errorf("no wrapper candidates found in %s", comparePath)
	}

	rawImports := make([]string, 0, len(usedImports))
	for spec := range usedImports {
		rawImports = append(rawImports, spec)
	}
	sort.Strings(rawImports)

	return templateData{Imports: rawImports, Functions: functions}, nil
}

// availableImports maps import names referenced in syntax to rendered import specs.
func availableImports(fset *token.FileSet, file *ast.File) (map[string]string, error) {
	imports := make(map[string]string, len(file.Imports))
	for _, spec := range file.Imports {
		importPath, err := strconv.Unquote(spec.Path.Value)
		if err != nil {
			return nil, err
		}

		name := path.Base(importPath)
		if spec.Name != nil {
			name = spec.Name.Name
		}

		raw, err := renderNode(fset, spec)
		if err != nil {
			return nil, err
		}

		imports[name] = raw
	}

	return imports, nil
}

// shouldWrap reports whether fn should be wrapped in the musta package.
func shouldWrap(fn *ast.FuncDecl) bool {
	if fn.Recv != nil || fn.Name == nil || !fn.Name.IsExported() {
		return false
	}

	params := fn.Type.Params
	if params == nil || len(params.List) == 0 {
		return false
	}

	first := params.List[0]
	if len(first.Names) != 1 || first.Names[0].Name != "tb" {
		return false
	}

	results := fn.Type.Results
	if results == nil || len(results.List) != 1 || len(results.List[0].Names) != 0 {
		return false
	}

	result, ok := results.List[0].Type.(*ast.Ident)
	return ok && result.Name == "bool"
}

// collectFunction builds template data for a wrapped function.
func collectFunction(fset *token.FileSet, fn *ast.FuncDecl) (functionData, error) {
	commentLines, err := collectCommentLines(fn)
	if err != nil {
		return functionData{}, err
	}

	typeParams, err := renderTypeParams(fset, fn.Type.TypeParams)
	if err != nil {
		return functionData{}, err
	}

	params, args, err := renderParams(fset, fn.Type.Params)
	if err != nil {
		return functionData{}, err
	}

	return functionData{
		CommentLines: commentLines,
		Name:         fn.Name.Name,
		TypeParams:   typeParams,
		Params:       params,
		Args:         args,
	}, nil
}

// collectCommentLines extracts documentation comment lines for fn.
func collectCommentLines(fn *ast.FuncDecl) ([]string, error) {
	if fn.Doc == nil {
		return nil, fmt.Errorf("missing doc comment")
	}

	text := strings.TrimSuffix(fn.Doc.Text(), "\n")
	if text == "" {
		return nil, fmt.Errorf("empty doc comment")
	}

	return strings.Split(text, "\n"), nil
}

// renderTypeParams renders function type parameters.
func renderTypeParams(fset *token.FileSet, fields *ast.FieldList) (string, error) {
	if fields == nil || len(fields.List) == 0 {
		return "", nil
	}

	params, err := renderFieldList(fset, fields)
	if err != nil {
		return "", err
	}

	return "[" + params + "]", nil
}

// renderParams renders the wrapper parameter list and call arguments.
func renderParams(fset *token.FileSet, fields *ast.FieldList) (string, string, error) {
	if fields == nil || len(fields.List) == 0 {
		return "", "", nil
	}

	params := make([]string, 0, len(fields.List))
	args := make([]string, 0, len(fields.List))
	for _, field := range fields.List {
		param, fieldArgs, err := renderField(fset, field)
		if err != nil {
			return "", "", err
		}

		params = append(params, param)
		args = append(args, fieldArgs...)
	}

	return strings.Join(params, ", "), strings.Join(args, ", "), nil
}

// renderField renders a single parameter field and the argument names it contributes.
func renderField(fset *token.FileSet, field *ast.Field) (string, []string, error) {
	typeSrc, err := renderNode(fset, field.Type)
	if err != nil {
		return "", nil, err
	}

	if len(field.Names) == 0 {
		return typeSrc, nil, nil
	}

	names := make([]string, 0, len(field.Names))
	for _, ident := range field.Names {
		names = append(names, ident.Name)
	}

	return strings.Join(names, ", ") + " " + typeSrc, names, nil
}

// renderFieldList renders a list of fields without surrounding delimiters.
func renderFieldList(fset *token.FileSet, fields *ast.FieldList) (string, error) {
	parts := make([]string, 0, len(fields.List))
	for _, field := range fields.List {
		part, _, err := renderField(fset, field)
		if err != nil {
			return "", err
		}

		parts = append(parts, part)
	}

	return strings.Join(parts, ", "), nil
}

// renderNode renders node back to Go source without type checking.
func renderNode(fset *token.FileSet, node any) (string, error) {
	var buf bytes.Buffer
	if err := printer.Fprint(&buf, fset, node); err != nil {
		return "", err
	}

	return buf.String(), nil
}

// collectUsedImports records imported package names referenced by fields.
func collectUsedImports(imports map[string]string, fields *ast.FieldList, used map[string]struct{}) {
	if fields == nil {
		return
	}

	ast.Inspect(fields, func(n ast.Node) bool {
		selector, ok := n.(*ast.SelectorExpr)
		if !ok {
			return true
		}

		ident, ok := selector.X.(*ast.Ident)
		if !ok {
			return true
		}

		spec, ok := imports[ident.Name]
		if ok {
			used[spec] = struct{}{}
		}

		return true
	})
}

// render executes the compare template and formats the generated source.
func render(data templateData) ([]byte, error) {
	tmpl, err := template.New("compare").Parse(compareTemplate)
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, err
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, err
	}

	return formatted, nil
}
