// Code generated by mustagen. DO NOT EDIT.

package musta

import (
	"github.com/AlekSi/shoulda"
	"github.com/AlekSi/shoulda/cmp"
)

// BeFalse checks that actual is false.
func BeFalse(tb TB, actual bool) {
	tb.Helper()

	if !shoulda.BeFalse(tb, actual) {
		tb.FailNow()
	}
}

// BeTrue checks that actual is true.
func BeTrue(tb TB, actual bool) {
	tb.Helper()

	if !shoulda.BeTrue(tb, actual) {
		tb.FailNow()
	}
}

// BeDeepEqual checks that actual and expected are equal according to [reflect.DeepEqual].
func BeDeepEqual(tb TB, actual, expected any) {
	tb.Helper()

	if !shoulda.BeDeepEqual(tb, actual, expected) {
		tb.FailNow()
	}
}

// NotBeDeepEqual checks that actual and expected are not equal according to [reflect.DeepEqual].
func NotBeDeepEqual(tb TB, actual, expected any) {
	tb.Helper()

	if !shoulda.NotBeDeepEqual(tb, actual, expected) {
		tb.FailNow()
	}
}

// BeEqual checks that actual and expected are equal according to [cmp.Equal].
func BeEqual[T cmp.Ordered](tb TB, actual, expected T) {
	tb.Helper()

	if !shoulda.BeEqual(tb, actual, expected) {
		tb.FailNow()
	}
}

// BeLess checks that actual is less than expected according to [cmp.Less].
func BeLess[T cmp.Ordered](tb TB, actual, expected T) {
	tb.Helper()

	if !shoulda.BeLess(tb, actual, expected) {
		tb.FailNow()
	}
}

// BeGreater checks that actual is greater than expected according to [cmp.Greater].
func BeGreater[T cmp.Ordered](tb TB, actual, expected T) {
	tb.Helper()

	if !shoulda.BeGreater(tb, actual, expected) {
		tb.FailNow()
	}
}

// Satisfy checks that predicate returns true for actual.
func Satisfy[T any](tb TB, actual T, predicate func(_ T) bool) {
	tb.Helper()

	if !shoulda.Satisfy(tb, actual, predicate) {
		tb.FailNow()
	}
}

// SatisfyWith checks that predicate returns true for actual and expected.
func SatisfyWith[T any](tb TB, actual, expected T, predicate func(_, _ T) bool) {
	tb.Helper()

	if !shoulda.SatisfyWith(tb, actual, expected, predicate) {
		tb.FailNow()
	}
}

// CompareWith checks that compare(actual, expected) returns order.
func CompareWith[T any](tb TB, actual, expected T, order cmp.Order, compare func(_, _ T) int) {
	tb.Helper()

	if !shoulda.CompareWith(tb, actual, expected, order, compare) {
		tb.FailNow()
	}
}

// CompareEqual checks that compare(actual, expected) returns 0 ([cmp.OrderEqual]).
func CompareEqual[T any](tb TB, actual, expected T, compare func(_, _ T) int) {
	tb.Helper()

	if !shoulda.CompareEqual(tb, actual, expected, compare) {
		tb.FailNow()
	}
}

// CompareLess checks that compare(actual, expected) returns -1 ([cmp.OrderLess]).
func CompareLess[T any](tb TB, actual, expected T, compare func(_, _ T) int) {
	tb.Helper()

	if !shoulda.CompareLess(tb, actual, expected, compare) {
		tb.FailNow()
	}
}

// CompareGreater checks that compare(actual, expected) returns 1 ([cmp.OrderGreater]).
func CompareGreater[T any](tb TB, actual, expected T, compare func(_, _ T) int) {
	tb.Helper()

	if !shoulda.CompareGreater(tb, actual, expected, compare) {
		tb.FailNow()
	}
}
