// Code generated by mustagen. DO NOT EDIT.

package musta

import (
	"time"

	"github.com/AlekSi/shoulda/cmp"
	"github.com/AlekSi/shoulda/internal"
)

// t is used by examples.
var t internal.TestTB

func ExampleBeDeepEqual() {
	BeDeepEqual(t, []int{13}, []int64{13})

	// Output:
	// Values are not deep equal:
	// actual:   []int{13}
	// expected: []int64{13}
	// FAIL
}

func ExampleSatisfy() {
	Satisfy(t, 13, func(v int) bool { return v > 42 })

	// Output:
	// predicate is not satisfied for
	// actual:   13
	// FAIL
}

func ExampleSatisfyWith_inline() {
	SatisfyWith(t, 13, 42, func(x, y int) bool { return x > y })

	// Output:
	// predicate is not satisfied with
	// actual:   13
	// expected: 42
	// FAIL
}

func ExampleSatisfyWith_function() {
	SatisfyWith(t, 13, 42, cmp.Greater)

	// Output:
	// predicate is not satisfied with
	// actual:   13
	// expected: 42
	// FAIL
}

func ExampleSatisfyWith_method() {
	actual := time.Date(2026, time.April, 9, 17, 32, 42, 123, time.UTC)
	expected := time.Date(2026, time.April, 9, 17, 32, 42, 123, time.FixedZone("My", 4*int(time.Hour.Seconds())))
	SatisfyWith(t, actual, expected, time.Time.Before)

	// Output:
	// predicate is not satisfied with
	// actual:   2026-04-09 17:32:42.000000123 +0000 UTC
	// expected: 2026-04-09 17:32:42.000000123 +0400 My
	// FAIL
}
