// Code generated by mustagen. DO NOT EDIT.

package musta

import (
	"github.com/AlekSi/shoulda"
)

// Error checks that actual is a non-nil error.
func Error(tb TB, actual error) {
	tb.Helper()

	if !shoulda.Error(tb, actual) {
		tb.FailNow()
	}
}

// Errorf checks that actual is a non-nil error.
func Errorf(tb TB, actual error, format string, args ...any) {
	tb.Helper()

	if !shoulda.Errorf(tb, actual, format, args...) {
		tb.FailNow()
	}
}

// NoError checks that actual is a nil error.
func NoError(tb TB, actual error) {
	tb.Helper()

	if !shoulda.NoError(tb, actual) {
		tb.FailNow()
	}
}

// NoErrorf checks that actual is a nil error.
func NoErrorf(tb TB, actual error, format string, args ...any) {
	tb.Helper()

	if !shoulda.NoErrorf(tb, actual, format, args...) {
		tb.FailNow()
	}
}
