// Code generated by mustagen. DO NOT EDIT.

package musta

import (
	"testing"
	"time"

	"github.com/AlekSi/shoulda/cmp"
)

func TestSatisfy(t *testing.T) {
	t.Run("Inline", func(t *testing.T) {
		tt, lines := setup(t)
		Satisfy(tt, 13, func(v int) bool { return v > 42 })

		BeDeepEqual(t, lines(), []string{
			"predicate is not satisfied for",
			"actual:   13",
			"FAIL",
		})
	})

	t.Run("MethodValue", func(t *testing.T) {
		tt, lines := setup(t)
		actual := time.Date(2026, time.April, 9, 17, 32, 42, 123, time.UTC)
		Satisfy(tt, actual, time.Now().Before)

		BeDeepEqual(t, lines(), []string{
			"predicate is not satisfied for",
			"actual:   2026-04-09 17:32:42.000000123 +0000 UTC",
			"FAIL",
		})
	})

	t.Run("MethodExpression", func(t *testing.T) {
		tt, lines := setup(t)
		actual := time.Date(2026, time.April, 9, 17, 32, 42, 123, time.UTC)
		Satisfy(tt, actual, time.Time.IsZero)

		BeDeepEqual(t, lines(), []string{
			"predicate is not satisfied for",
			"actual:   2026-04-09 17:32:42.000000123 +0000 UTC",
			"FAIL",
		})
	})
}

func TestSatisfyWith(t *testing.T) {
	t.Run("Inline", func(t *testing.T) {
		tt, lines := setup(t)
		SatisfyWith(tt, 13, 42, func(x, y int) bool { return x > y })

		BeDeepEqual(t, lines(), []string{
			"predicate is not satisfied with",
			"actual:   13",
			"expected: 42",
			"FAIL",
		})
	})

	t.Run("Function", func(t *testing.T) {
		tt, lines := setup(t)
		SatisfyWith(tt, 13, 42, cmp.Greater)

		BeDeepEqual(t, lines(), []string{
			"predicate is not satisfied with",
			"actual:   13",
			"expected: 42",
			"FAIL",
		})
	})

	t.Run("MethodExpression", func(t *testing.T) {
		tt, lines := setup(t)
		actual := time.Date(2026, time.April, 9, 17, 32, 42, 123, time.UTC)
		expected := time.Date(2026, time.April, 9, 17, 32, 42, 123, time.FixedZone("My", 4*int(time.Hour.Seconds())))
		SatisfyWith(tt, actual, expected, time.Time.Before)

		BeDeepEqual(t, lines(), []string{
			"predicate is not satisfied with",
			"actual:   2026-04-09 17:32:42.000000123 +0000 UTC",
			"expected: 2026-04-09 17:32:42.000000123 +0400 My",
			"FAIL",
		})
	})
}

func TestCompareWith(t *testing.T) {
	t.Run("Function", func(t *testing.T) {
		tt, lines := setup(t)
		CompareWith(tt, 42, 13, cmp.OrderLess, cmp.Compare[int])

		BeDeepEqual(t, lines(), []string{
			"comparison result is not -1 for",
			"actual:   42",
			"expected: 13",
			"FAIL",
		})
	})
}

func TestCompareEqual(t *testing.T) {
	t.Run("MethodExpression", func(t *testing.T) {
		tt, lines := setup(t)
		actual := time.Date(2026, time.April, 9, 17, 32, 42, 123, time.UTC)
		expected := time.Date(2026, time.April, 9, 17, 32, 42, 123, time.FixedZone("My", 4*int(time.Hour.Seconds())))
		CompareEqual(tt, actual, expected, time.Time.Compare)

		BeDeepEqual(t, lines(), []string{
			"comparison result is greater, not equal for",
			"actual:   2026-04-09 17:32:42.000000123 +0000 UTC",
			"expected: 2026-04-09 17:32:42.000000123 +0400 My",
			"FAIL",
		})
	})
}

func TestCompareLess(t *testing.T) {
	t.Run("MethodExpression", func(t *testing.T) {
		tt, lines := setup(t)
		actual := time.Date(2026, time.April, 9, 17, 32, 42, 123, time.UTC)
		expected := time.Date(2026, time.April, 9, 17, 32, 42, 123, time.FixedZone("My", 4*int(time.Hour.Seconds())))
		CompareLess(tt, actual, expected, time.Time.Compare)

		BeDeepEqual(t, lines(), []string{
			"comparison result is greater, not less for",
			"actual:   2026-04-09 17:32:42.000000123 +0000 UTC",
			"expected: 2026-04-09 17:32:42.000000123 +0400 My",
			"FAIL",
		})
	})
}

func TestCompareGreater(t *testing.T) {
	t.Run("MethodExpression", func(t *testing.T) {
		tt, lines := setup(t)
		actual := time.Date(2026, time.April, 9, 17, 32, 42, 123, time.FixedZone("My", 4*int(time.Hour.Seconds())))
		expected := time.Date(2026, time.April, 9, 17, 32, 42, 123, time.UTC)
		CompareGreater(tt, actual, expected, time.Time.Compare)

		BeDeepEqual(t, lines(), []string{
			"comparison result is less, not greater for",
			"actual:   2026-04-09 17:32:42.000000123 +0400 My",
			"expected: 2026-04-09 17:32:42.000000123 +0000 UTC",
			"FAIL",
		})
	})
}
