// Code generated by mustagen. DO NOT EDIT.

package musta

import (
	"time"

	"github.com/AlekSi/shoulda/cmp"
)

func ExampleSatisfy_inline() {
	Satisfy(t, 13, func(v int) bool { return v > 42 })

	// Output:
	// predicate is not satisfied for
	// actual:   13
	// FAIL
}

func ExampleSatisfy_methodValue() {
	actual := time.Date(2026, time.April, 9, 17, 32, 42, 123, time.UTC)
	Satisfy(t, actual, time.Now().Before)

	// Output:
	// predicate is not satisfied for
	// actual:   2026-04-09 17:32:42.000000123 +0000 UTC
	// FAIL
}

func ExampleSatisfy_methodExpression() {
	actual := time.Date(2026, time.April, 9, 17, 32, 42, 123, time.UTC)
	Satisfy(t, actual, time.Time.IsZero)

	// Output:
	// predicate is not satisfied for
	// actual:   2026-04-09 17:32:42.000000123 +0000 UTC
	// FAIL
}

func ExampleSatisfyWith_inline() {
	SatisfyWith(t, 13, 42, func(x, y int) bool { return x > y })

	// Output:
	// predicate is not satisfied with
	// actual:   13
	// expected: 42
	// FAIL
}

func ExampleSatisfyWith_function() {
	SatisfyWith(t, 13, 42, cmp.Greater)

	// Output:
	// predicate is not satisfied with
	// actual:   13
	// expected: 42
	// FAIL
}

func ExampleSatisfyWith_methodExpression() {
	actual := time.Date(2026, time.April, 9, 17, 32, 42, 123, time.UTC)
	expected := time.Date(2026, time.April, 9, 17, 32, 42, 123, time.FixedZone("My", 4*int(time.Hour.Seconds())))
	SatisfyWith(t, actual, expected, time.Time.Before)

	// Output:
	// predicate is not satisfied with
	// actual:   2026-04-09 17:32:42.000000123 +0000 UTC
	// expected: 2026-04-09 17:32:42.000000123 +0400 My
	// FAIL
}
