// Code generated by mustagen. DO NOT EDIT.

package musta

import (
	"github.com/AlekSi/shoulda"
	"github.com/AlekSi/shoulda/cmp"
)

// Satisfy checks that predicate returns true for actual.
func Satisfy[A any](tb TB, actual A, predicate func(_ A) bool) {
	tb.Helper()

	if !shoulda.Satisfy(tb, actual, predicate) {
		tb.FailNow()
	}
}

// Satisfyf checks that predicate returns true for actual.
func Satisfyf[A any](tb TB, actual A, predicate func(_ A) bool, format string, args ...any) {
	tb.Helper()

	if !shoulda.Satisfyf(tb, actual, predicate, format, args...) {
		tb.FailNow()
	}
}

// SatisfyWith checks that predicate returns true for actual and expected.
func SatisfyWith[A, E any](tb TB, actual A, expected E, predicate func(_ A, _ E) bool) {
	tb.Helper()

	if !shoulda.SatisfyWith(tb, actual, expected, predicate) {
		tb.FailNow()
	}
}

// SatisfyWithf checks that predicate returns true for actual and expected.
func SatisfyWithf[A, E any](tb TB, actual A, expected E, predicate func(_ A, _ E) bool, format string, args ...any) {
	tb.Helper()

	if !shoulda.SatisfyWithf(tb, actual, expected, predicate, format, args...) {
		tb.FailNow()
	}
}

// CompareWith checks that compare(actual, expected) returns order.
func CompareWith[A, E any](tb TB, actual A, expected E, order cmp.Order, compare func(_ A, _ E) int) {
	tb.Helper()

	if !shoulda.CompareWith(tb, actual, expected, order, compare) {
		tb.FailNow()
	}
}

// CompareWithf checks that compare(actual, expected) returns order.
func CompareWithf[A, E any](tb TB, actual A, expected E, order cmp.Order, compare func(_ A, _ E) int, format string, args ...any) {
	tb.Helper()

	if !shoulda.CompareWithf(tb, actual, expected, order, compare, format, args...) {
		tb.FailNow()
	}
}

// CompareEqual checks that compare(actual, expected) returns 0 ([cmp.OrderEqual]).
func CompareEqual[A, E any](tb TB, actual A, expected E, compare func(_ A, _ E) int) {
	tb.Helper()

	if !shoulda.CompareEqual(tb, actual, expected, compare) {
		tb.FailNow()
	}
}

// CompareEqualf checks that compare(actual, expected) returns 0 ([cmp.OrderEqual]).
func CompareEqualf[A, E any](tb TB, actual A, expected E, compare func(_ A, _ E) int, format string, args ...any) {
	tb.Helper()

	if !shoulda.CompareEqualf(tb, actual, expected, compare, format, args...) {
		tb.FailNow()
	}
}

// CompareLess checks that compare(actual, expected) returns -1 ([cmp.OrderLess]).
func CompareLess[A, E any](tb TB, actual A, expected E, compare func(_ A, _ E) int) {
	tb.Helper()

	if !shoulda.CompareLess(tb, actual, expected, compare) {
		tb.FailNow()
	}
}

// CompareLessf checks that compare(actual, expected) returns -1 ([cmp.OrderLess]).
func CompareLessf[A, E any](tb TB, actual A, expected E, compare func(_ A, _ E) int, format string, args ...any) {
	tb.Helper()

	if !shoulda.CompareLessf(tb, actual, expected, compare, format, args...) {
		tb.FailNow()
	}
}

// CompareGreater checks that compare(actual, expected) returns 1 ([cmp.OrderGreater]).
func CompareGreater[A, E any](tb TB, actual A, expected E, compare func(_ A, _ E) int) {
	tb.Helper()

	if !shoulda.CompareGreater(tb, actual, expected, compare) {
		tb.FailNow()
	}
}

// CompareGreaterf checks that compare(actual, expected) returns 1 ([cmp.OrderGreater]).
func CompareGreaterf[A, E any](tb TB, actual A, expected E, compare func(_ A, _ E) int, format string, args ...any) {
	tb.Helper()

	if !shoulda.CompareGreaterf(tb, actual, expected, compare, format, args...) {
		tb.FailNow()
	}
}
