// Code generated by mustagen. DO NOT EDIT.

package musta

import (
	"github.com/AlekSi/shoulda"
	"github.com/AlekSi/shoulda/cmp"
)

// Satisfy checks that predicate returns true for actual.
func Satisfy[A any](tb TB, actual A, predicate func(_ A) bool) {
	tb.Helper()

	if !shoulda.Satisfy(tb, actual, predicate) {
		tb.FailNow()
	}
}

// Satisfyf checks that predicate returns true for actual.
func Satisfyf[A any](tb TB, actual A, predicate func(_ A) bool, format string, args ...any) {
	tb.Helper()

	if !shoulda.Satisfyf(tb, actual, predicate, format, args...) {
		tb.FailNow()
	}
}

// NotSatisfy checks that predicate returns false for actual.
func NotSatisfy[A any](tb TB, actual A, predicate func(_ A) bool) {
	tb.Helper()

	if !shoulda.NotSatisfy(tb, actual, predicate) {
		tb.FailNow()
	}
}

// NotSatisfyf checks that predicate returns false for actual.
func NotSatisfyf[A any](tb TB, actual A, predicate func(_ A) bool, format string, args ...any) {
	tb.Helper()

	if !shoulda.NotSatisfyf(tb, actual, predicate, format, args...) {
		tb.FailNow()
	}
}

// SatisfyWith checks that predicate returns true for actual and expected.
func SatisfyWith[A, E any](tb TB, actual A, expected E, predicate func(_ A, _ E) bool) {
	tb.Helper()

	if !shoulda.SatisfyWith(tb, actual, expected, predicate) {
		tb.FailNow()
	}
}

// SatisfyWithf checks that predicate returns true for actual and expected.
func SatisfyWithf[A, E any](tb TB, actual A, expected E, predicate func(_ A, _ E) bool, format string, args ...any) {
	tb.Helper()

	if !shoulda.SatisfyWithf(tb, actual, expected, predicate, format, args...) {
		tb.FailNow()
	}
}

// NotSatisfyWith checks that predicate returns false for actual and expected.
func NotSatisfyWith[A, E any](tb TB, actual A, expected E, predicate func(_ A, _ E) bool) {
	tb.Helper()

	if !shoulda.NotSatisfyWith(tb, actual, expected, predicate) {
		tb.FailNow()
	}
}

// NotSatisfyWithf checks that predicate returns false for actual and expected.
func NotSatisfyWithf[A, E any](tb TB, actual A, expected E, predicate func(_ A, _ E) bool, format string, args ...any) {
	tb.Helper()

	if !shoulda.NotSatisfyWithf(tb, actual, expected, predicate, format, args...) {
		tb.FailNow()
	}
}

// CompareEqual checks that compare(actual, expected) returns 0 ([cmp.OrderEqual]).
func CompareEqual[A, E any](tb TB, actual A, expected E, compare func(_ A, _ E) int) {
	tb.Helper()

	if !shoulda.CompareEqual(tb, actual, expected, compare) {
		tb.FailNow()
	}
}

// CompareEqualf checks that compare(actual, expected) returns 0 ([cmp.OrderEqual]).
func CompareEqualf[A, E any](tb TB, actual A, expected E, compare func(_ A, _ E) int, format string, args ...any) {
	tb.Helper()

	if !shoulda.CompareEqualf(tb, actual, expected, compare, format, args...) {
		tb.FailNow()
	}
}

// CompareLess checks that compare(actual, expected) returns -1 ([cmp.OrderLess]).
func CompareLess[A, E any](tb TB, actual A, expected E, compare func(_ A, _ E) int) {
	tb.Helper()

	if !shoulda.CompareLess(tb, actual, expected, compare) {
		tb.FailNow()
	}
}

// CompareLessf checks that compare(actual, expected) returns -1 ([cmp.OrderLess]).
func CompareLessf[A, E any](tb TB, actual A, expected E, compare func(_ A, _ E) int, format string, args ...any) {
	tb.Helper()

	if !shoulda.CompareLessf(tb, actual, expected, compare, format, args...) {
		tb.FailNow()
	}
}

// CompareGreater checks that compare(actual, expected) returns 1 ([cmp.OrderGreater]).
func CompareGreater[A, E any](tb TB, actual A, expected E, compare func(_ A, _ E) int) {
	tb.Helper()

	if !shoulda.CompareGreater(tb, actual, expected, compare) {
		tb.FailNow()
	}
}

// CompareGreaterf checks that compare(actual, expected) returns 1 ([cmp.OrderGreater]).
func CompareGreaterf[A, E any](tb TB, actual A, expected E, compare func(_ A, _ E) int, format string, args ...any) {
	tb.Helper()

	if !shoulda.CompareGreaterf(tb, actual, expected, compare, format, args...) {
		tb.FailNow()
	}
}

// NotPanic checks that f does not panic.
func NotPanic(tb TB, f func()) {
	tb.Helper()

	if !shoulda.NotPanic(tb, f) {
		tb.FailNow()
	}
}

// NotPanicf checks that f does not panic.
func NotPanicf(tb TB, f func(), format string, args ...any) {
	tb.Helper()

	if !shoulda.NotPanicf(tb, f, format, args...) {
		tb.FailNow()
	}
}

// PanicSatisfy checks that f panics with the value of type A.
// If predicate is not nil, it also checks that the panic value satisfies it.
func PanicSatisfy[A any](tb TB, predicate func(_ A) bool, f func()) {
	tb.Helper()

	if !shoulda.PanicSatisfy(tb, predicate, f) {
		tb.FailNow()
	}
}

// PanicSatisfyf checks that f panics with the value of type A.
// If predicate is not nil, it also checks that the panic value satisfies it.
func PanicSatisfyf[A any](tb TB, predicate func(_ A) bool, f func(), format string, args ...any) {
	tb.Helper()

	if !shoulda.PanicSatisfyf(tb, predicate, f, format, args...) {
		tb.FailNow()
	}
}

// Keep reference for links in documentation comments.
var (
	_ cmp.Order = 0
)
