// Code generated by mustagen. DO NOT EDIT.

package musta

import "github.com/AlekSi/shoulda/internal"

// t is used by examples.
var t internal.TestTB

func ExampleBeDeepEqualf() {
	BeDeepEqualf(t, []int{13}, []int64{13}, "extra message: %s, %d", "foo", 42)

	// Output:
	// actual is not deep equal to expected:
	// actual: []int{
	//   13,
	// } ([]int)
	// expected: []int64{
	//   13,
	// } ([]int64)
	// diff expected actual
	// --- expected
	// +++ actual
	// @@ -1,3 +1,3 @@
	// -[]int64{
	// +[]int{
	//    13,
	// -} ([]int64)
	// +} ([]int)
	// extra message: foo, 42
	// FAIL
}

func ExampleBeEqualf() {
	BeEqualf(t, 13, 42, "extra message: %s, %d", "foo", 42)

	// Output:
	// actual is not equal to expected:
	// actual: 13 (int)
	// expected: 42 (int)
	// diff expected actual
	// --- expected
	// +++ actual
	// @@ -1,1 +1,1 @@
	// -42 (int)
	// +13 (int)
	// extra message: foo, 42
	// FAIL
}

func ExampleNotBeEqualf() {
	NotBeEqualf(t, 13, 13, "extra message: %s, %d", "foo", 42)

	// Output:
	// actual is equal to expected:
	// actual: 13 (int)
	// expected: 13 (int)
	// extra message: foo, 42
	// FAIL
}

func ExampleNotBeDeepEqualf() {
	NotBeDeepEqualf(t, []int{13}, []int{13}, "extra message: %s, %d", "foo", 42)

	// Output:
	// actual is deep equal to expected:
	// actual: []int{
	//   13,
	// } ([]int)
	// expected: []int{
	//   13,
	// } ([]int)
	// extra message: foo, 42
	// FAIL
}
