// Code generated by mustagen. DO NOT EDIT.

package musta

import (
	"github.com/AlekSi/shoulda"
)

// BeNil checks that actual is untyped nil.
func BeNil(tb TB, actual any) {
	tb.Helper()

	if !shoulda.BeNil(tb, actual) {
		tb.FailNow()
	}
}

// NotBeNil checks that actual is not (untyped) nil.
func NotBeNil(tb TB, actual any) {
	tb.Helper()

	if !shoulda.NotBeNil(tb, actual) {
		tb.FailNow()
	}
}

// BeZero checks that actual is the zero value of its type.
func BeZero[T comparable](tb TB, actual T) {
	tb.Helper()

	if !shoulda.BeZero(tb, actual) {
		tb.FailNow()
	}
}

// NotBeZero checks that actual is not the zero value of its type.
func NotBeZero[T comparable](tb TB, actual T) {
	tb.Helper()

	if !shoulda.NotBeZero(tb, actual) {
		tb.FailNow()
	}
}
