// Code generated by mustagen. DO NOT EDIT.

package musta

import (
	"errors"
	"testing"
)

func TestBeNil(t *testing.T) {
	t.Run("Value", func(t *testing.T) {
		tt, actual := setup(t)
		BeNil(tt, 13)

		BeDeepEqual(t, actual(), []string{
			"actual is not nil, but int:",
			"13",
			"FAIL",
		})
	})

	t.Run("UntypedNil", func(t *testing.T) {
		tt, actual := setup(t)
		BeNil(tt, nil)

		BeDeepEqual(t, actual(), []string{""})
	})

	t.Run("TypedNil", func(t *testing.T) {
		tt, actual := setup(t)
		BeNil(tt, (*int)(nil))

		BeDeepEqual(t, actual(), []string{
			"actual is not nil, but *int:",
			"nil",
			"FAIL",
		})
	})

	t.Run("Error", func(t *testing.T) {
		tt, actual := setup(t)
		BeNil(tt, errors.New("boom"))

		BeDeepEqual(t, actual(), []string{
			"actual is not nil, but *errors.errorString:",
			`&errors.errorString{`,
			`  s: "boom",`,
			`}`,
			"FAIL",
		})
	})
}

func TestNotBeNil(t *testing.T) {
	t.Run("UntypedNil", func(t *testing.T) {
		tt, actual := setup(t)
		NotBeNil(tt, nil)

		BeDeepEqual(t, actual(), []string{
			"actual is nil",
			"FAIL",
		})
	})

	t.Run("TypedNil", func(t *testing.T) {
		tt, actual := setup(t)
		NotBeNil(tt, (*int)(nil))

		BeDeepEqual(t, actual(), []string{""})
	})

	t.Run("Pointer", func(t *testing.T) {
		tt, actual := setup(t)
		BeZero(tt, new(13))

		BeDeepEqual(t, actual(), []string{
			"actual is not zero, but *int:",
			"&13",
			"FAIL",
		})
	})
}

func TestBeZero(t *testing.T) {
	t.Run("Simple", func(t *testing.T) {
		tt, actual := setup(t)
		BeZero(tt, 13)

		BeDeepEqual(t, actual(), []string{
			"actual is not zero, but int:",
			"13",
			"FAIL",
		})
	})
}

func TestNotBeZero(t *testing.T) {
	t.Run("Simple", func(t *testing.T) {
		tt, actual := setup(t)
		NotBeZero(tt, 0)

		BeDeepEqual(t, actual(), []string{
			"actual is zero",
			"FAIL",
		})
	})
}
