// Code generated by mustagen. DO NOT EDIT.

package musta

import (
	"errors"
	"testing"
)

func TestBeNil(t *testing.T) {
	t.Run("Value", func(t *testing.T) {
		tt, actual := setup(t)
		BeNil(tt, uint32(13))

		BeDeepEqual(t, actual(), []string{
			"actual is not untyped nil, but uint32:",
			"13",
			"FAIL",
		})
	})

	t.Run("Pointer", func(t *testing.T) {
		tt, actual := setup(t)
		BeNil(tt, new(uint32(13)))

		BeDeepEqual(t, actual(), []string{
			"actual is not untyped nil, but *uint32:",
			"&13",
			"FAIL",
		})
	})

	t.Run("UntypedNil", func(t *testing.T) {
		tt, actual := setup(t)
		BeNil(tt, nil)

		BeDeepEqual(t, actual(), []string{""})
	})

	t.Run("TypedNil", func(t *testing.T) {
		tt, actual := setup(t)
		BeNil(tt, (*uint32)(nil))

		BeDeepEqual(t, actual(), []string{
			"actual is not untyped nil, but *uint32:",
			"nil",
			"FAIL",
		})
	})

	t.Run("Error", func(t *testing.T) {
		tt, actual := setup(t)
		BeNil(tt, errors.New("boom"))

		BeDeepEqual(t, actual(), []string{
			"actual is not untyped nil, but *errors.errorString:",
			`&errors.errorString{`,
			`  s: "boom",`,
			`}`,
			"FAIL",
		})
	})
}

func TestNotBeNil(t *testing.T) {
	t.Run("Value", func(t *testing.T) {
		tt, actual := setup(t)
		NotBeNil(tt, uint32(13))

		BeDeepEqual(t, actual(), []string{""})
	})

	t.Run("Pointer", func(t *testing.T) {
		tt, actual := setup(t)
		NotBeNil(tt, new(uint32(13)))

		BeDeepEqual(t, actual(), []string{""})
	})

	t.Run("UntypedNil", func(t *testing.T) {
		tt, actual := setup(t)
		NotBeNil(tt, nil)

		BeDeepEqual(t, actual(), []string{
			"actual is untyped nil",
			"FAIL",
		})
	})

	t.Run("TypedNil", func(t *testing.T) {
		tt, actual := setup(t)
		NotBeNil(tt, (*uint32)(nil))

		BeDeepEqual(t, actual(), []string{""})
	})

	t.Run("Error", func(t *testing.T) {
		tt, actual := setup(t)
		NotBeNil(tt, errors.New("boom"))

		BeDeepEqual(t, actual(), []string{""})
	})
}

func TestBeZero(t *testing.T) {
	t.Run("Simple", func(t *testing.T) {
		tt, actual := setup(t)
		BeZero(tt, 13)

		BeDeepEqual(t, actual(), []string{
			"actual is not zero, but int:",
			"13",
			"FAIL",
		})
	})

	t.Run("Nil", func(t *testing.T) {
		tt, actual := setup(t)
		BeZero(tt, (*int)(nil))

		BeDeepEqual(t, actual(), []string{""})
	})
}

func TestNotBeZero(t *testing.T) {
	t.Run("Simple", func(t *testing.T) {
		tt, actual := setup(t)
		NotBeZero(tt, 0)

		BeDeepEqual(t, actual(), []string{
			"actual is zero",
			"FAIL",
		})
	})

	t.Run("Nil", func(t *testing.T) {
		tt, actual := setup(t)
		NotBeZero(tt, (*int)(nil))

		BeDeepEqual(t, actual(), []string{
			"actual is zero",
			"FAIL",
		})
	})
}

func TestError(t *testing.T) {
	t.Run("Simple", func(t *testing.T) {
		tt, actual := setup(t)
		Error(tt, errors.New("boom"))

		BeDeepEqual(t, actual(), []string{""})
	})

	t.Run("Nil", func(t *testing.T) {
		tt, actual := setup(t)
		Error(tt, nil)

		BeDeepEqual(t, actual(), []string{
			"actual is not error, but <nil>:",
			"nil",
			"FAIL",
		})
	})
}

func TestNoError(t *testing.T) {
	t.Run("Simple", func(t *testing.T) {
		tt, actual := setup(t)
		NoError(tt, errors.New("boom"))

		BeDeepEqual(t, actual(), []string{
			"actual is error: boom",
			"FAIL",
		})
	})

	t.Run("Nil", func(t *testing.T) {
		tt, actual := setup(t)
		NoError(tt, nil)

		BeDeepEqual(t, actual(), []string{""})
	})
}
