// Code generated by mustagen. DO NOT EDIT.

package musta

import "testing"

func TestBeZero(t *testing.T) {
	t.Run("Simple", func(t *testing.T) {
		tt, actual := setup(t)
		BeZero(tt, 13)

		BeDeepEqual(t, actual(), []string{
			"actual is not zero, but:",
			"actual: 13 (int)",
			"FAIL",
		})
	})

	t.Run("Nil", func(t *testing.T) {
		tt, actual := setup(t)
		BeZero(tt, (*int)(nil))

		BeDeepEqual(t, actual(), []string{""})
	})
}

func TestBeZerof(t *testing.T) {
	tt, actual := setup(t)
	BeZerof(tt, 13, "extra message: %s, %d", "foo", 42)

	BeDeepEqual(t, actual(), []string{
		"actual is not zero, but:",
		"actual: 13 (int)",
		"extra message: foo, 42",
		"FAIL",
	})
}

func TestNotBeZero(t *testing.T) {
	t.Run("Simple", func(t *testing.T) {
		tt, actual := setup(t)
		NotBeZero(tt, 0)

		BeDeepEqual(t, actual(), []string{
			"actual is zero",
			"FAIL",
		})
	})

	t.Run("Nil", func(t *testing.T) {
		tt, actual := setup(t)
		NotBeZero(tt, (*int)(nil))

		BeDeepEqual(t, actual(), []string{
			"actual is zero",
			"FAIL",
		})
	})
}

func TestNotBeZerof(t *testing.T) {
	tt, actual := setup(t)
	NotBeZerof(tt, 0, "extra message: %s, %d", "foo", 42)

	BeDeepEqual(t, actual(), []string{
		"actual is zero",
		"extra message: foo, 42",
		"FAIL",
	})
}
